common: &COMMON
  encoding: utf8
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: changelog_prod
  username: changelog
  password: PRODUCTION_PASSWORD

development:
  <<: *COMMON
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *COMMON
  adapter: sqlite3
  database: db/test.sqlite3
